# This workflow will trigger on a daily basis to check aws cdk version, update them if needed and creates a pull request when its done.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: npm audit fix commit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-dir: '.'
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      
    - uses: grandmasterdev/npm-audit-fix@latest
      with:
        working-dir: ${{github.workspace}}
        github-user: 'action-committer'
        github-email: 'action-committer'
        github-token: ${{github.token}}
        github-remote: 'origin'
